# Generated by Django 3.1 on 2022-02-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('sofa', 'sofa'), ('bed', 'bed'), ('kids', 'kids'), ('armchair', 'armchair'), ('chair', 'chair'), ('table', 'table')], max_length=20),
        ),
    ]
