# Generated by Django 3.1 on 2022-02-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='kkal',
        ),
    ]
